export const SAVE_NAME_VALUE = "SAVE_NAME_VALUE";
export const SAVE_EMAIL_VALUE = "SAVE_EMAIL_VALUE";
export const SAVE_PASSWORD_VALUE = "SAVE_PASSWORD_VALUE";
export const SAVE_PASSWORD_REPEAT_VALUE = "SAVE_PASSWORD_REPEAT_VALUE";
