export const SAVE_NAME_VALUE = "SAVE_NAME_VALUE";
export const SAVE_EMAIL_VALUE = "SAVE_EMAIL_VALUE";
export const SAVE_PASSWORD_VALUE = "SAVE_PASSWORD_VALUE";
export const SAVE_PASSWORD2_VALUE = "SAVE_PASSWORD2_VALUE";

export const GET_SERVER_SIDE_ERRORS = "GET_SERVER_SIDE_ERRORS";
export const CLEAR_SERVER_SIDE_ERRORS = "CLEAR_SERVER_SIDE_ERRORS";

export const SET_USER = "SET_USER";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
