export const SAVE_NAME_VALUE = "SAVE_NAME_VALUE";
export const SAVE_EMAIL_VALUE = "SAVE_EMAIL_VALUE";
export const SAVE_PASSWORD_VALUE = "SAVE_PASSWORD_VALUE";
export const SAVE_PASSWORD2_VALUE = "SAVE_PASSWORD2_VALUE";

export const REGISTER_USER = "REGISTER_USER";

export const GET_SERVER_SIDE_ERRORS = "GET_SERVER_SIDE_ERRORS";
export const CLEAR_SERVER_SIDE_ERRORS = "CLEAR_SERVER_SIDE_ERRORS";

export const LOGIN_USER = "LOGIN_USER";
